name: My First Workflows

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome Message
          run: echo "My First Github Action Tab"
          
        - name: list files
          run: ls
          
        - name: Read files
          run: cat README.md


