name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        
        - name: List and Read
          run:
            echo "My FIrst Github Actions Job"
            ls -ltra
            cat README.md

        - name: ASCII Art
          run: cowsay -f dragon "Run for cover, I am a DRAGON....Fire" >> dragon.txt


        # - name: Welcome Message
        #   run: echo "My FIrst Github Actions Job"

        # - name: list files
        #   run: ls

        # - name: Read File
        #   run: cat README.md


